#!/data/data/com.termux/files/usr/bin/env bash
#=============================================================================
# basic.bash --- basic script files
# Copyright (c) 2016-2021 nvspc & EasyQuest
# Author: Ivan Yastrebov < easy-quest@mail.ru >
# URL: https://easyquest.host
#=============================================================================

if ! pgrep okc-ssh-agent > /dev/null; then
	okc-ssh-agent > "$PREFIX/tmp/okc-ssh-agent.env"
fi
source "$PREFIX/tmp/okc-ssh-agent.env"

